[package]
name = "quickexif"
version = "0.1.0"
edition = "2021"

description = "A rust library to parse EXIF data from images"
keywords = ["exif", "tiff", "jpeg"]
documentation = "https://docs.rs/quickexif"
repository = "https://github.com/qdwang/quickexif"
license-file = "LICENSE"

[dependencies]
thiserror = "1"

